### ISSUE TITLE
Wait Time Algorithm

### ISSUE THREAD

**Issue by nugentmichael1** [FS-CSCI150-F21/FS-CSCI150-F21-Team1#12]
Use Raspberry Pi's people counter data (an integer) -- strored in mySQL database -- to design an algorithm that predicts customer wait times.

**Comment by lhn1703** [comment]
Complete, the computer will now take the sum of current order prep time, and update the number of guests waiting in line, as well as the total number of occupants whenever the computer vision algorithm detects any person entering or leaving.
